---
title: "Visualization Final Report"
author: "Jacob Saindon"
format: 
  html: 
    theme: darkly
---

```{r}
library(tidyverse)
library(ggrepel)
library(patchwork)
set.seed(500)
```

Source: https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-01-25/readme.md

```{r}
ratings <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-25/ratings.csv')
```

```{r}
#| fig-width: 8
#| fig-height: 8
rate_plot<-ggplot(subset(ratings, rank %in% c(1:50)),aes(x=average,y=reorder(name,-rank),size=users_rated))+
  geom_point()+
  # geom_text_repel(aes(label=rank), size=2.5, color="black", fontface="italic")+
  scale_x_continuous(limits=c(7.5, 9),position="top")+
  scale_y_discrete(position="left")+
  theme_minimal()+
  theme(legend.position="top",plot.title=element_text(hjust = 0.5))+
  labs(x="Average Rating (out of 10)",
       y="Game Ranking (1st ranked at top, 50th at bottom)",
       size="Number of Reviews",
       title="Top 50-Ranked Board Games by Rating and Number of Reviews",
       subtitle="According to Board Game Geek, 2022",
       caption="Visualized by Jacob Saindon, Feb. 2023\nData from TidyTuesday by way of Board Game Geek\nhttps://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-01-25/readme.md")

rate_plot
```

<!-- \^Top 25 ranked board games sorted by average user score (out of 10) -->

<!-- ```{r} -->

<!-- num_plot<-ggplot(subset(ratings, rank %in% c(1:25)),aes(x=(users_rated/1000),y=reorder(abbreviate(name),users_rated/1000)))+ -->

<!--   geom_point()+ -->

<!--   geom_text(aes(label=(users_rated/1000), hjust=-0.5), size=2.5, color="black", fontface="italic")+ -->

<!--   scale_x_continuous(limits=c(0, 90),name="Number of Reviewers (thousands)")+ -->

<!--   scale_y_discrete(name=NULL)+ -->

<!--   theme_minimal() -->

<!-- ``` -->

<!-- \^Top 25 ranked board games sorted by user ratings (1000s) -->

<!-- ```{r} -->

<!-- combo_plot<-ggplot(subset(ratings, rank %in% c(1:25)),aes(x=(users_rated/1000),y=average))+ -->

<!--   geom_point()+ -->

<!--   geom_text_repel(aes(label=abbreviate(name),vjust=-0.2, hjust=-0.2), size=2.5, color="black",fontface="bold")+ -->

<!--   scale_x_continuous(limits=c(0, 80), name="Number of Reviewers (thousands)")+ -->

<!--   scale_y_continuous(limits=c(8, 9.0), name="Average Rating (out of 10)")+ -->

<!--   theme_minimal() -->

<!-- combo_plot -->

<!-- ``` -->

<!-- \^Top 25 ranked board games: average user score (out of 10) x total number of user ratings (1000s) -->

<!-- ```{r} -->

<!-- trio_plot<-combo_plot / (rate_plot | num_plot) -->

<!-- ``` -->

<!-- ```{r} -->

<!-- #| fig-width: 12 -->

<!-- #| fig-height: 8 -->

<!-- trio_plot+ -->

<!--   plot_annotation( -->

<!--     title="Top 25 Ranked Board Games by Rating and Review Volume", -->

<!--     subtitle=str_wrap("According to Board Game Geek, 2022",width=50), -->

<!--     caption="Visualized by Jacob Saindon, Feb. 2023\nData from TidyTuesday by way of Board Game Geek\nhttps://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-01-25/readme.md", -->

<!--     theme = theme(plot.title = element_text(size=24, family="Times"),plot.subtitle = element_text(size=16, family="Times"), plot.caption = element_text(size=10, family="Times"))) -->

<!-- ``` -->

To-Do: resize points, adjust text labels
